nixPkgs = ["nodejs_20", "python3", "gcc", "gnumake"]

[phases.install]
cmds = [
  "ln -s $(which python3) /usr/bin/python || true",
  "npm install --legacy-peer-deps"
]

[phases.build]
cmds = ["echo 'No build step needed'"]

[start]
cmd = "npm run start:railway"