nixPkgs = ["nodejs_20", "python3", "gcc", "gnumake"]

[phases.install]
cmds = [
  "ln -sf /usr/bin/python3 /usr/bin/python || true",
  "PYTHON=/usr/bin/python3 npm install --legacy-peer-deps"
]

[phases.build]
cmds = ["echo 'No build step needed'"]

[start]
cmd = "npm run start:railway"