[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run start:railway"
healthcheckPath = "/api"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "group-status-backend"

[services.variables]
NODE_ENV = "production"
PORT = "${{ PORT }}"